#
# 스프링 프로파일 그룹화
#
spring:
  profiles:
    group:
      dev: common, local

---

#
# 공통 환경 설정
#

spring:
  config:
    activate:
      on-profile:
        - common
  main:
    # 스프링 부트 서버 런타임시 출력되는 시작 배너 끄기
    banner-mode: off
  # 웹 브라우저 새로고침을 통한 화면단 변경된 내용을 적용하기 위한 뷰파일 경로 설정
  thymeleaf:
    prefix: file:src/main/resources/templates/
    suffix: .html
    cache: false  # 개발 완료시 false 변경
  # 웹 브라우저 새로고침을 통한 화면단 변경된 내용을 적용하기 위한 웹 정적 리소스 파일 경로 설정
  web:
    resources:
      static-locations:
        - file:src/main/resources/static/

# 마이바티스 설정
mybatis:
  # 마이바티스 런타임시 동작 제어를 위한 값 설정
  configuration:
    cache-enabled: false
    lazy-loading-enabled: false
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    jdbc-type-for-null: NULL
    local-cache-scope: STATEMENT
  # 별칭 지정 : 매퍼 XML 파일에서 반환 및 파라미터 타입 지정시 패키지 경로 생략 처리하고 클래스명만 기입
  type-aliases-package: com.sukong.scrum.domain.**.dto
  # 별도의 타입 핸들러가 포함된 패키지 경로를 지정함으로 해당 타입 핸들러를 등록 처리
  type-handlers-package: com.sukong.scrum.global.common.mybatis
  # 매퍼 XML 파일 경로 지정
  mapper-locations:
    - classpath:mappers/**/*_mapper.xml

# 서버 설정
server:
  port: 90
  servlet:
    # HTTP 요청 및 응답 인코딩 설정
    encoding:
      charset: UTF-8
      enabled: true
      force: true

---

#
# 로컬 개발 환경 설정
#

spring:
  config:
    activate:
      on-profile:
        - local
  # 데이터베이스 연결 정보 설정
  datasource:
    url: jdbc:mariadb://localhost:3306/scrum?characterEncoding=UTF-8&serverTimeZone=Asia/Seoul
    username: master
    password: 5033
    driver-class-name: org.mariadb.jdbc.Driver

# 개발 전용 로깅 레벨 지정
logging:
  level:
    web: debug
    sql: debug
    root: info




