-- #--------------------------------------------------------------------------------------------------
-- #	테이블 생성
-- #--------------------------------------------------------------------------------------------------



-- TABLE NAME 	: 사용자 테이블 (USERS)
-- DESCRIPTION	: 회원가입 정보(필수)만 저장 및 관리하는 테이블
CREATE TABLE USERS (
	USER_ID				BIGINT				NOT NULL AUTO_INCREMENT COMMENT '사용자 번호',
	ID					VARCHAR(20)			NOT NULL COMMENT '사용자 아이디',
	PASSWORD			VARCHAR(255)		NOT NULL COMMENT '비밀번호',
	NAME				VARCHAR(12)  		NOT NULL COMMENT '이름',
	EMAIL				VARCHAR(40)			NOT NULL COMMENT '이메일',
	LOGIN_TYPE			VARCHAR(5)			NOT NULL COMMENT '로그인 유형(LOCAL: 자체 가입 방식을 이용한 로그인 / OAUTH: 소셜 연동을 통한 로그인)',
	ENABELD				TINYINT(1)			NOT NULL COMMENT '계정의 활성화',
	CREATED_AT			DATETIME 			NOT NULL DEFAULT NOW() COMMENT '가입일자',
	UPDATED_AT			DATETIME			NOT NULL COMMENT '변경일자',
	PRIMARY KEY (USER_ID)
) ENGINE = INNODB DEFAULT CHARSET = UTF8MB4 COMMENT '사용자 테이블';



-- TABLE NAME 	: 프로필 테이블 (PROFILES)
-- DESCRIPTION	: 회원가입 정보 외의 기타 정보들(사용자 정보 상세 내용, 필수x)을 저장 및 관리하는 테이블
CREATE TABLE PROFILES (
	PROFILE_ID			BIGINT				NOT NULL AUTO_INCREMENT COMMENT '프로필 번호',
	USER_ID				BIGINT				NOT NULL COMMENT '사용자 번호',
	IMAGE_NAME			VARCHAR(200)		NOT NULL COMMENT '프로필 이미지 파일 이름',
	IMAGE_URL			VARCHAR(255)		NOT NULL COMMENT '프로필 이미지 파일 경로',
	IMAGE_SIZE			BIGINT				NOT NULL COMMENT '프로필 이미지 파일 크기',
	INTRODUCTION		TEXT				NOT NULL COMMENT '자기 소개글',
	UNIV_NAME			VARCHAR(45)			NOT NULL COMMENT '출신 대학명',
	CITY_NAME			VARCHAR(30)			NOT NULL COMMENT '거주 도시명',
	CREATED_AT			DATETIME 			NOT NULL DEFAULT NOW() COMMENT '등록일자',
	UPDATED_AT			DATETIME 			NOT NULL COMMENT '변경일자',
	PRIMARY KEY (PROFILE_ID),
	FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE = INNODB DEFAULT CHARSET = UTF8MB4 COMMENT '프로필 테이블';



-- TABLE NAME 	: 사용자별 권한 테이블 (USER_ROLES)
-- DESCRIPTION	: 회원별로 부여된 권한들을 저장 및 관리하는 테이블로 한 명의 회원당 여러 개의 권한을 저장할 수 있음.
CREATE TABLE USER_ROLES (
	USER_ID				BIGINT				NOT NULL COMMENT '사용자 번호',
	ROLE				VARCHAR(25)			NOT NULL COMMENT '권한 코드명 (ROLE_USER : 일반회원 / ROLE_ADMIN : 시스템 관리자',
	USE_YN				CHAR(1)				NOT NULL COMMENT '권한 사용여부',
	CREATED_AT			DATETIME 			NOT NULL DEFAULT NOW() COMMENT '등록일자',
	UPDATED_AT			DATETIME 			NOT NULL COMMENT '변경일자',
	FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE = INNODB DEFAULT CHARSET = UTF8MB4 COMMENT '사용자별 권한 테이블';



-- TABLE NAME 	: 팀 테이블 (TEAMS)
-- DESCRIPTION	: 프로젝트 진행을 위한 팀에 대한 정보를 저장 및 관리하는 테이블
CREATE TABLE TEAMS (
	TEAM_ID				BIGINT				NOT NULL AUTO_INCREMENT COMMENT '팀 번호',
	NAME				VARCHAR(100)		NOT NULL COMMENT '팀명',
	INTRODUCTION		TEXT				NOT NULL COMMENT '팀소개글',
	CREATED_AT			DATETIME 			NOT NULL DEFAULT NOW() COMMENT '등록일자',
	UPDATED_AT			DATETIME 			NOT NULL COMMENT '변경일자',
	DELETE_YN			CHAR(1)				NOT NULL COMMENT '삭제여부',
	PRIMARY KEY (TEAM_ID)
) ENGINE = INNODB DEFAULT CHARSET = UTF8MB4 COMMENT '팀 테이블';



-- TABLE NAME 	: 팀원 테이블 (TEAM_USERS)
-- DESCRIPTION	: 팀에 소속되는 팀원들에 대한 정보를 저장 및 관리하는 테이블
CREATE TABLE TEAM_USERS (
	TEAM_ID				BIGINT				NOT NULL COMMENT '팀 번호',
	USER_ID				BIGINT				NOT NULL COMMENT '사용자 번호',
	IS_CAPTAIN			CHAR(1)				NOT NULL COMMENT '팀장 여부 (Y : 팀장 / N : 팀원)',
	FIELD				CHAR(2)				NOT NULL COMMENT '자신의 주 분야 (BE : 백엔드 개발 / FE : 프런트 개발 / FS : 풀스택 개발)',
	CREATED_AT 			DATETIME 			NOT NULL DEFAULT NOW() COMMENT '등록일자',
	UPDATED_AT			DATETIME 			NOT NULL COMMENT '변경일자',
	FOREIGN KEY (TEAM_ID) REFERENCES TEAMS (TEAM_ID) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE = INNODB DEFAULT CHARSET = UTF8MB4 COMMENT '팀원 테이블';



-- TABLE NAME 	: 프로젝트 정보 테이블 (PROJECTS)
-- DESCRIPTION	: 팀이 진행할 프로젝트에 대한 정보를 저장 및 관리하는 테이블
CREATE TABLE PROJECTS (
	PROJECT_ID			BIGINT				NOT NULL AUTO_INCREMENT COMMENT '프로젝트 번호',
	NAME				VARCHAR(150)		NOT NULL COMMENT '프로젝트 명',
	PROJECT_TYPE		VARCHAR(12)			NOT NULL COMMENT '프로젝트 분야',
	TEAM_ID				BIGINT				NOT NULL COMMENT '프로제트 팀 번호',
	PROJECT_MANAGER_ID	BIGINT				NOT NULL COMMENT '프로젝트 매니저 번호',
	INTRODUCTION		TEXT				NOT NULL COMMENT '프로젝트 소개글',
	START_DATE			DATE 				NOT NULL COMMENT '프로젝트 시작일',
	END_DATE			DATE				NOT NULL COMMENT '프로젝트 종료일',
	CREATED_AT 			DATETIME 			NOT NULL DEFAULT NOW() COMMENT '등록일자',
	UPDATED_AT			DATETIME 			NOT NULL COMMENT '변경일자',
	PROJECT_STATUS		CHAR(1)				NOT NULL COMMENT '프로젝트 상태 (W : 대기 중 / P : 진행 중/ D : 종료)',
	DELETE_YN			CHAR(1)				NOT NULL COMMENT '삭제여부',
	PRIMARY KEY (PROJECT_ID),
	FOREIGN KEY (TEAM_ID) REFERENCES TEAMS (TEAM_ID) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (PROJECT_MANAGER_ID) REFERENCES USERS (USER_ID) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE = INNODB DEFAULT CHARSET = UTF8MB4 COMMENT '프로젝트 정보 테이블';