-- # ==========================================================================================================
-- # 	테이블 정의
-- # ==========================================================================================================


-- TABLE NAME : 사용자 테이블 / USERS
CREATE TABLE USERS (
	USER_ID						BIGINT						NOT NULL AUTO_INCREMENT COMMENT '사용자 번호',
	ID							VARCHAR(20)					NOT NULL COMMENT '아이디',
	PASSWORD					VARCHAR(255)				NOT NULL COMMENT '비밀번호',
	NAME						VARCHAR(12)					NOT NULL COMMENT '이름',
	EMAIL						VARCHAR(40)					NOT NULL COMMENT '이메일',
	LOGIN_TYPE					VARCHAR(5)					NOT NULL COMMENT '로그인 유형',
	ENABLED						TINYINT(1)					NOT NULL COMMENT '계정 활성화 (1:활성화/0:비활성화)',
	DELETE_YN					CHAR(1)						NOT NULL DEFAULT 'N' COMMENT '삭제 여부',
	CREATED_AT					DATETIME					NOT NULL DEFAULT NOW() COMMENT '가입일자',
	UPDATED_AT					DATETIME					NOT NULL COMMENT '변경일자',
	PRIMARY KEY (USER_ID)
) ENGINE = INNODB DEFAULT CHARSET = UTF8MB4 COMMENT '사용자 테이블';


-- TABLE NAME : 사용자 권한 테이블 / USER_ROLES
CREATE TABLE USER_ROLES (
	USER_ID						BIGINT						NOT NULL COMMENT '사용자 번호',
	ROLE						VARCHAR(25)					NOT NULL COMMENT '권한 코드명',
	USE_YN						CHAR(1)						NOT NULL COMMENT '권한 사용 여부',
	DELETE_YN					CHAR(1)						NOT NULL DEFAULT 'N' COMMENT '삭제 여부',
	CREATED_AT					DATETIME					NOT NULL DEFAULT NOW() COMMENT '권한 등록 일자',
	UPDATED_AT					DATETIME					NOT NULL COMMENT '권한 변경 일자',
	FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE = INNODB DEFAULT CHARSET = UTF8MB4 COMMENT '사용자 권한 테이블';


-- TABLE NAME : 프로필 테이블 / PROFILES
CREATE TABLE PROFILES (
	PROFILE_ID					BIGINT						NOT NULL AUTO_INCREMENT COMMENT '프로필 번호',
	USER_ID						BIGINT						NULL COMMENT '사용자 번호',
	PROFILE_IMG_NAME			VARCHAR(250)				NULL COMMENT '프로필 이미지 파일 이름(*.확장자명)',
	PROFILE_IMG_URL				VARCHAR(255)				NULL COMMENT '프로필 이미지 파일 경로',
	PROFILE_IMG_SIZE			INT							NULL COMMENT '프로필 이미지 파일 크기',
	UNIV						VARCHAR(35) 				NOT NULL COMMENT '출신 대학교명',
	CITY						VARCHAR(22)					NOT NULL COMMENT '거주 도시명',
	CREATED_AT					DATETIME					NOT NULL DEFAULT NOW() COMMENT '프로필 등록 일자',
	UPDATED_AT					DATETIME					NOT NULL COMMENT '프로필 변경 일자',
	PRIMARY KEY (PROFILE_ID),
	FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE = INNODB DEFAULT CHARSET = UTF8MB4 COMMENT '프로필 테이블';


-- TABLE NAME : 팀 테이블 / TEAMS
CREATE TABLE TEAMS (
	TEAM_ID						BIGINT						NOT NULL AUTO_INCREMENT COMMENT '팀 번호',
	NAME						VARCHAR(100)				NOT NULL COMMENT '팀 명',
	INTRODUCTION				TEXT						NOT NULL COMMENT '팀 소개글',
	USE_YN						CHAR(1)						NOT NULL COMMENT '팀 사용 여부',
	DELETE_YN					CHAR(1)						NOT NULL DEFAULT 'N' COMMENT '팀 삭제 여부',
	CREATED_AT					DATETIME					NOT NULL DEFAULT NOW() COMMENT '팀 정보 등록 일자',
	UPDATED_AT					DATETIME					NOT NULL COMMENT '팀 정보 변경 일자',
	PRIMARY KEY (TEAM_ID)
) ENGINE = INNODB DEFAULT CHARSET = UTF8MB4 COMMENT '팀 테이블';


-- TABLE NAME : 팀원 테이블 / TEAM_USERS
CREATE TABLE TEAM_USERS (
	TEAM_USER_ID				BIGINT						NOT NULL AUTO_INCREMENT COMMENT '팀원 번호',
	TEAM_ID						BIGINT						NOT NULL COMMENT '팀 번호',
	USER_ID						BIGINT						NOT NULL COMMENT '사용자 번호',
	IS_CAPTAIN					CHAR(1)						NOT NULL COMMENT '팀장여부',
	DEV_TYPE					VARCHAR(2)					NOT NULL COMMENT '개발 분야 (BE:백엔드/FE:프런트엔드/FS:풀스택)',
	CREATED_AT					DATETIME					NOT NULL DEFAULT NOW() COMMENT '팀원 등록 일자',
	UPDATED_AT					DATETIME					NOT NULL COMMENT '팀원 변경 일자',
	PRIMARY KEY (TEAM_USER_ID),
	FOREIGN KEY (TEAM_ID) REFERENCES TEAMS (TEAM_ID) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE = INNODB DEFAULT CHARSET = UTF8MB4 COMMENT '팀원 테이블';


-- TABLE NAME : 프로젝트 정보 테이블 / PROJECTS
CREATE TABLE PROJECTS (
	PROJECT_ID					BIGINT						NOT NULL AUTO_INCREMENT COMMENT '프로젝트 번호',
	NAME						VARCHAR(150)				NOT NULL COMMENT '프로젝트 이름',
	PROJECT_TYPE				VARCHAR(10)					NOT NULL COMMENT '프로젝트 유형 (WEB:웹/MOBILE:모바일/IOT:IOT/API:API/ETC:기타)',
	TEAM_ID						BIGINT						NOT NULL COMMENT '팀 번호',
	USER_ID						BIGINT						NOT NULL COMMENT '프로젝트 관리자 번호',
	INTRODUCTION				TEXT						NOT NULL COMMENT '프로젝트 소개글',
	START_DATE					DATETIME					NOT NULL COMMENT '프로젝트 시작 일자',
	END_DATE					DATETIME					NOT NULL COMMENT '프로젝트 종료 일자',
	STATUS						CHAR(1)						NOT NULL COMMENT '프로젝트 상태',
	CREATED_AT					DATETIME					NOT NULL DEFAULT NOW() COMMENT '프로젝트 정보 등록 일자',
	UPDATED_AT					DATETIME					NOT NULL COMMENT '프로젝트 정보 변경 일자',
	DELETE_YN					CHAR(1)						NOT NULL DEFAULT 'N' COMMENT '프로젝트 삭제 여부',
	PRIMARY KEY (PROJECT_ID),
	FOREIGN KEY (TEAM_ID) REFERENCES TEAMS (TEAM_ID) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE = INNODB DEFAULT CHARSET = UTF8MB4 COMMENT '프로젝트 정보 테이블';


-- TABLE NAME : 상위 업무 그룹 테이블 / TASK_GROUPS
CREATE TABLE TASK_GROUPS (
	TASK_GROUP_ID				BIGINT						NOT NULL AUTO_INCREMENT COMMENT '업무 그룹 번호',
	NAME						VARCHAR(30)					NOT NULL COMMENT '업무 그룹 명',
	SORT						INT							NOT NULL COMMENT '화면상 정렬 번호',
	USE_YN						CHAR(1)						NOT NULL COMMENT '사용 여부',
	CREATED_AT					DATETIME					NOT NULL DEFAULT NOW() COMMENT '등록 일자',
	UPDATED_AT					DATETIME					NOT NULL COMMENT '변경 일자',
	PRIMARY KEY (TASK_GROUP_ID)
) ENGINE = INNODB DEFAULT CHARSET = UTF8MB4 COMMENT '상위 업무 그룹 테이블';

INSERT INTO TASK_GROUPS (
	NAME,
	SORT,
	USE_YN,
	UPDATED_AT
) VALUES
    ('요구사항 분석', 1, 'Y', NOW()),
    ('설계', 2, 'Y', NOW()),
    ('구현', 3, 'Y', NOW()),
    ('테스트', 4, 'Y', NOW()),
    ('유지보수', 5, 'Y', NOW());


-- TABLE NAME : 프로젝트 업무 테이블 / PROJECT_TASKS
CREATE TABLE PROJECT_TASKS (
	PROJECT_TASK_ID				BIGINT						NOT NULL AUTO_INCREMENT COMMENT '프로젝트 업무 번호',
	PROJECT_ID					BIGINT						NOT NULL COMMENT '프로젝트 번호',
	TASK_GROUP_ID				BIGINT						NOT NULL COMMENT '상위 업무 그룹 번호',
	NAME						VARCHAR(100)				NOT NULL COMMENT '업무 명',
	SORT						INT							NOT NULL COMMENT '화면상 정렬 번호',
	START_DATE					DATETIME					NOT NULL COMMENT '업무 시작 일자',
	END_DATE					DATETIME					NOT NULL COMMENT '업무 종료 일자',
	REAL_END_DATE				DATETIME					NOT NULL COMMENT '실제 업무 종료 일자',
	RATE						INT							NOT NULL COMMENT '업무 진행률',
	DELETE_YN					CHAR(1)						NOT NULL DEFAULT 'N' COMMENT '삭제 여부',
	CREATED_AT					DATETIME					NOT NULL DEFAULT NOW() COMMENT '업무 등록 일자',
	UPDATED_AT					DATETIME					NOT NULL COMMENT '업무 변경 일자',
	PRIMARY KEY (PROJECT_TASK_ID),
	FOREIGN KEY (PROJECT_ID) REFERENCES PROJECTS (PROJECT_ID) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (TASK_GROUP_ID) REFERENCES TASK_GROUPS (TASK_GROUP_ID) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE = INNODB DEFAULT CHARSET = UTF8MB4 COMMENT '프로젝트 업무 테이블';


-- TABLE NAME : 프로젝트 업무 할당 테이블 / TASK_USERS
CREATE TABLE TASK_USERS (
	PROJECT_TASK_ID				BIGINT						NOT NULL COMMENT '프로젝트 업무 번호',
	USER_ID						BIGINT						NOT NULL COMMENT '사용자 번호',
	FOREIGN KEY (PROJECT_TASK_ID) REFERENCES PROJECT_TASKS (PROJECT_TASK_ID) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE = INNODB DEFAULT CHARSET = UTF8MB4 COMMENT '프로젝트 업무 할당 테이블';